name: Blob storage website CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Blob Storage
        run: |
          az storage blob upload-batch --account-name gavinazureresume --auth-mode key -d '$web' -s . --overwrite
        working-directory: ${{ github.workspace }}

      - name: Purge CDN Endpoint
        run: |
          az cdn endpoint purge --content-paths "/*" --profile-name gavinazureresume --name gavinazureresume --resource-group gavinazureresume-rg --no-wait
        working-directory: ${{ github.workspace }}

      - name: Azure Logout
        run: az logout
        if: always()
